# This config file will have limits and system information for the robot controller
# It provides an extra level of safety for sending joint commands to the robot hardware

desktop_arm_controller_node:
  ros__parameters:
    controller_joint_names: ['joint_1', 'joint_2', 'joint_3', 'joint_4', 'joint_5']
    joint_step: 1.0 # in degrees
    publishing_rate: 1.0 # Hz
    joint_1:
      min_lim: 0.0 
      max_lim: 1.0
    joint_2:
      min_lim: 0.0 
      max_lim: 1.0
    joint_3:
      min_lim: 0.0 
      max_lim: 1.0
    joint_4:
      min_lim: 0.0 
      max_lim: 1.0
    joint_5:
      min_lim: 0.0 
      max_lim: 1.0

